export enum CONTROLLER_TYPE {
  CLASSIC = 'CLASSIC',
  MODERN = 'MODERN',
}

export enum NODE_KIND {
  NUMPAD_BLOCK = 'NUMPAD_BLOCK',
  CHARACTER_MOVE_IMAGE = 'CHARACTER_MOVE_IMAGE',
  ARROW = 'ARROW',
  ARROW_ANCHOR = 'ARROW_ANCHOR',
  TEXT = 'TEXT',
  VIDEO = 'VIDEO',
}
