// This file is auto-generated by @hey-api/openapi-ts

/**
 * GoogleLoginBody
 */
export type GoogleLoginBody = {
    /**
     * Id Token
     */
    id_token: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Picture
     */
    picture: string | null;
    /**
     * Google Sub
     */
    google_sub: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UserGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type UserGetMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UserGetMeResponse = UserGetMeResponses[keyof UserGetMeResponses];

export type UserIsYouThereData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/user/search/{email}';
};

export type UserIsYouThereErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserIsYouThereError = UserIsYouThereErrors[keyof UserIsYouThereErrors];

export type UserIsYouThereResponses = {
    /**
     * Response User-Is You There
     * Successful Response
     */
    200: boolean;
};

export type UserIsYouThereResponse = UserIsYouThereResponses[keyof UserIsYouThereResponses];

export type AuthGoogleLoginData = {
    body: GoogleLoginBody;
    path?: never;
    query?: never;
    url: '/auth/google-login';
};

export type AuthGoogleLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthGoogleLoginError = AuthGoogleLoginErrors[keyof AuthGoogleLoginErrors];

export type AuthGoogleLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};